### ISSUE TITLE
No runnable satisfies the requirement for a FullTextTEIExtractor

### ISSUE THREAD

**Issue by fanchyna** [SeerLabs/pdfmef#2]
In python_wrapper/properties.config, I set 
fulltext_tei_to_csx: True
and got the following error message. What is exactly a "FullTextTEIExtractor"?

```
Traceback (most recent call last):
  File "main.py", line 155, in <module>
    runner.run_from_file_batch(files, outputPaths, num_processes=numProcesses, file_prefixes=prefixes)
  File "/usr/lib/python2.6/site-packages/extraction/core.py", line 201, in run_from_file_batch
    e.get()
  File "/usr/lib64/python2.6/multiprocessing/pool.py", line 422, in get
    raise self._value
LookupError: No runnable satisfies the requirement for a FullTextTEIExtractor

```

**Comment by huaiyudavid** [comment]
did you set fulltext to true?

**Comment by fanchyna** [comment]
Yes, I did.

**Comment by huaiyudavid** [comment]
Ok, so after taking another look at the code, it seems that "fulltext_tei_to_csx" depends on the option above it, namely "fulltext_grobid". the grobid fulltext extractor qualifies as the dependency that it needs, which is a FullTextTEIExtractor. You should set grobid to true.

**Comment by fanchyna** [comment]
David,

I did set "grobid" to true. Here is the full properties.config file. Is
there anywhere I mis-configured?

Thanks
Jian
